source 'https://rubygems.org'

gem 'typhoeus'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'activerecord'
gem 'twilio-ruby'
gem 'pg'
gem 'validates_phone_number'
gem 'dotenv'
